swagger: '2.0'
info:
  description: 'Order - API, This app controls the orders sended to sqs stock of the store'
  version: 1.0.0
  title: Orders
  contact:
    email: dutra.raysa@gmail.com
tags:
  - name: Health Check
    description: Orders operations
  - name: Health-Check
    description: Checks if the application it`s up
schemes:
  - https
  - http
paths:
  /health-check:
    get:
      tags:
        - Health-Check
      summary: It checks if the application it`s up
      description: Get an 200 if it`s alive
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/message'
  /order:
    get:
      tags:
        - Orders
      summary: It gets an array with all your orders
      description: List all orders
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/orders'
        '500':
          description: internal server error
          schema:
            $ref: '#/definitions/message'
    post:
      tags:
        - Orders
      summary: It create a order
      description: Create a Order
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Important information
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/orders'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/message'
        '500':
          description: internal server error
          schema:
            $ref: '#/definitions/message'
  '/order/{id}':
    get:
      tags:
        - Orders
      summary: Get order by id
      description: Get a unique check made using his id
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: Id of the order
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/orders'
        '400':
          description: Invalid id supplied
          schema:
            $ref: '#/definitions/message'
        '404':
          description: Id not found
          schema:
            $ref: '#/definitions/message'
    put:
      tags:
        - Orders
      summary: Update order by id
      description: Update a unique check made using his id
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: Id of the order
          required: true
          type: string
        - in: body
          name: body
          description: Important information
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/orders'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/message'
        '400':
          description: Invalid id supplied
          schema:
            $ref: '#/definitions/message'
        '404':
          description: Id not found
          schema:
            $ref: '#/definitions/message'
    delete:
      tags:
        - Orders
      summary: Delete order by id
      description: Delete a unique check made using his id
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: Id of the order
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/message'
        '400':
          description: Invalid id supplied
          schema:
            $ref: '#/definitions/message'
        '404':
          description: Id not found
          schema:
            $ref: '#/definitions/message'
definitions:
  message:
    type: string
    description: A message appears informing something
  orders:
    type: object
    required:
      - id_toy
      - quantity
    properties:
      id:
        type: integer
        format: int64
      id_toy:
        type: integer
        format: int64
      quantity:
        type: integer
        format: int64